In [20]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [21]:
data = pd.read_csv('/content/kddcup99_csv.csv')

In [22]:
print(data.head())

   duration protocol_type  ... dst_host_srv_rerror_rate   label
0         0           tcp  ...                      0.0  normal
1         0           tcp  ...                      0.0  normal
2         0           tcp  ...                      0.0  normal
3         0           tcp  ...                      0.0  normal
4         0           tcp  ...                      0.0  normal

[5 rows x 42 columns]

In [23]:
data.describe()

            duration  ...  dst_host_srv_rerror_rate
count  494020.000000  ...             494020.000000
mean       47.979400  ...                  0.057412
std       707.747185  ...                  0.230141
min         0.000000  ...                  0.000000
25%         0.000000  ...                  0.000000
50%         0.000000  ...                  0.000000
75%         0.000000  ...                  0.000000
max     58329.000000  ...                  1.000000

[8 rows x 38 columns]

In [25]:
data.shape

(494020, 42)

In [27]:
icmp = data[data.loc[:,"protocol_type"]=="icmp"]

In [28]:
icmp.head()

     duration protocol_type  ... dst_host_srv_rerror_rate   label
818         0          icmp  ...                      0.0  normal
819         0          icmp  ...                      0.0  normal
820         0          icmp  ...                      0.0  normal
821         0          icmp  ...                      0.0  normal
833         0          icmp  ...                      0.0  normal

[5 rows x 42 columns]